root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o ./tmp/main.exe main.go"
bin = "./tmp/main.exe -p 3000"
delay = 1000 # ms
exclude_dir = ["assets", "tmp", "vendor", "public"]
include_ext = ["go", "tpl", "tmpl", "html", "json"]
exclude_regex = ["_test\\.go"]